/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller */

#ifndef _Included_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
#define _Included_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    createFSEventStream
 * Signature: (JLjava/lang/String;DJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_createFSEventStream
  (JNIEnv *, jobject, jlong, jstring, jdouble, jlong);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    stopFSEventsStream
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_stopFSEventsStream
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    createSignalSource
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_createSignalSource
  (JNIEnv *, jobject);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    cfRunLoopSignal
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_cfRunLoopSignal
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    cfRunLoopGetCurrent
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_cfRunLoopGetCurrent
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    cfRunLoopRunWithSignalSource
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_cfRunLoopRunWithSignalSource
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    cfRunLoopStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_cfRunLoopStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventIdSinceNow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventIdSinceNow
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamCreateFlagNone
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamCreateFlagNone
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamCreateFlagUseCFTypes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamCreateFlagUseCFTypes
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamCreateFlagNoDefer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamCreateFlagNoDefer
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamCreateFlagWatchRoot
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamCreateFlagWatchRoot
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamCreateFlagIgnoreSelf
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamCreateFlagIgnoreSelf
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamCreateFlagFileEvents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamCreateFlagFileEvents
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamCreateFlagMarkSelf
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamCreateFlagMarkSelf
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagNone
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagNone
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagMustScanSubDirs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagMustScanSubDirs
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagUserDropped
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagUserDropped
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagKernelDropped
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagKernelDropped
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagEventIdsWrapped
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagEventIdsWrapped
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagHistoryDone
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagHistoryDone
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagRootChanged
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagRootChanged
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagMount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagMount
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagUnmount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagUnmount
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemCreated
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemCreated
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemRemoved
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemRemoved
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemInodeMetaMod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemInodeMetaMod
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemRenamed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemRenamed
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemModified
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemModified
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemFinderInfoMod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemFinderInfoMod
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemChangeOwner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemChangeOwner
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemXattrMod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemXattrMod
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemIsFile
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemIsFile
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemIsDir
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemIsDir
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemIsSymlink
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemIsSymlink
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagOwnEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagOwnEvent
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemIsHardlink
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemIsHardlink
  (JNIEnv *, jclass);

/*
 * Class:     edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_Poller
 * Method:    kFSEventStreamEventFlagItemIsLastHardlink
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_nccu_plsm_watchservice_MacOSXWatchServiceImpl_00024Poller_kFSEventStreamEventFlagItemIsLastHardlink
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
