/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_nccu_plsm_watchservice_SunNioFsUnixException */

#ifndef _Included_edu_nccu_plsm_watchservice_SunNioFsUnixException
#define _Included_edu_nccu_plsm_watchservice_SunNioFsUnixException
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_nccu_plsm_watchservice_SunNioFsUnixException_serialVersionUID
#define edu_nccu_plsm_watchservice_SunNioFsUnixException_serialVersionUID -3042686055658047285LL
#undef edu_nccu_plsm_watchservice_SunNioFsUnixException_serialVersionUID
#define edu_nccu_plsm_watchservice_SunNioFsUnixException_serialVersionUID -3387516993124229948LL
#undef edu_nccu_plsm_watchservice_SunNioFsUnixException_serialVersionUID
#define edu_nccu_plsm_watchservice_SunNioFsUnixException_serialVersionUID 7227016794320723218LL
#undef edu_nccu_plsm_watchservice_SunNioFsUnixException_EACCES
#define edu_nccu_plsm_watchservice_SunNioFsUnixException_EACCES 13L
#undef edu_nccu_plsm_watchservice_SunNioFsUnixException_ENOENT
#define edu_nccu_plsm_watchservice_SunNioFsUnixException_ENOENT 2L
#undef edu_nccu_plsm_watchservice_SunNioFsUnixException_EEXIST
#define edu_nccu_plsm_watchservice_SunNioFsUnixException_EEXIST 17L
#undef edu_nccu_plsm_watchservice_SunNioFsUnixException_ELOOP
#define edu_nccu_plsm_watchservice_SunNioFsUnixException_ELOOP 62L
/*
 * Class:     edu_nccu_plsm_watchservice_SunNioFsUnixException
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_nccu_plsm_watchservice_SunNioFsUnixException_strerror
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
